#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v16
# autospec commit: b858a2a
#
Name     : perl-DBIx-Class-DeploymentHandler
Version  : 0.002234
Release  : 35
URL      : https://cpan.metacpan.org/authors/id/W/WE/WESM/DBIx-Class-DeploymentHandler-0.002234.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/W/WE/WESM/DBIx-Class-DeploymentHandler-0.002234.tar.gz
Summary  : 'Extensible DBIx::Class deployment'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-DBIx-Class-DeploymentHandler-license = %{version}-%{release}
Requires: perl-DBIx-Class-DeploymentHandler-perl = %{version}-%{release}
Requires: perl-SQL-SplitStatement
BuildRequires : buildreq-cpan
BuildRequires : perl(Carp::Clan)
BuildRequires : perl(Context::Preserve)
BuildRequires : perl(DBD::SQLite)
BuildRequires : perl(DBIx::Class)
BuildRequires : perl(Log::Contextual)
BuildRequires : perl(Module::Runtime)
BuildRequires : perl(Moose)
BuildRequires : perl(MooseX::Role::Parameterized)
BuildRequires : perl(Path::Class)
BuildRequires : perl(SQL::SplitStatement)
BuildRequires : perl(SQL::Translator)
BuildRequires : perl(Sub::Exporter::Progressive)
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Test::Requires)
BuildRequires : perl(Text::Brew)
BuildRequires : perl(Try::Tiny)
BuildRequires : perl(YAML)
BuildRequires : perl(aliased)
BuildRequires : perl(namespace::autoclean)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
DBIx::Class::DeploymentHandler - Extensible DBIx::Class deployment
SYNOPSIS
use aliased 'DBIx::Class::DeploymentHandler' => 'DH';
my $s = My::Schema->connect(...);

%package dev
Summary: dev components for the perl-DBIx-Class-DeploymentHandler package.
Group: Development
Provides: perl-DBIx-Class-DeploymentHandler-devel = %{version}-%{release}
Requires: perl-DBIx-Class-DeploymentHandler = %{version}-%{release}

%description dev
dev components for the perl-DBIx-Class-DeploymentHandler package.


%package license
Summary: license components for the perl-DBIx-Class-DeploymentHandler package.
Group: Default

%description license
license components for the perl-DBIx-Class-DeploymentHandler package.


%package perl
Summary: perl components for the perl-DBIx-Class-DeploymentHandler package.
Group: Default
Requires: perl-DBIx-Class-DeploymentHandler = %{version}-%{release}

%description perl
perl components for the perl-DBIx-Class-DeploymentHandler package.


%prep
%setup -q -n DBIx-Class-DeploymentHandler-0.002234
cd %{_builddir}/DBIx-Class-DeploymentHandler-0.002234
pushd ..
cp -a DBIx-Class-DeploymentHandler-0.002234 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-DBIx-Class-DeploymentHandler
cp %{_builddir}/DBIx-Class-DeploymentHandler-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-DBIx-Class-DeploymentHandler/1cd106da592604cedae90f3f3a1aa0c8b15165dc || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/DBIx::Class::DeploymentHandler.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::Dad.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator::Deprecated.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator::ScriptHelpers.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::Deprecated.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::HandlesDeploy.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::HandlesVersionStorage.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::HandlesVersioning.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::Manual::CatalystIntro.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::Manual::Intro.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::Types.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::VersionHandler::DatabaseToSchemaVersions.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::VersionHandler::ExplicitVersions.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::VersionHandler::Monotonic.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::VersionStorage::Deprecated.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::VersionStorage::Deprecated::Component.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::VersionStorage::Deprecated::VersionResult.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::VersionStorage::Deprecated::VersionResultSet.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::VersionStorage::Standard.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::VersionStorage::Standard::Component.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResultSet.3
/usr/share/man/man3/DBIx::Class::DeploymentHandler::WithReasonableDefaults.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-DBIx-Class-DeploymentHandler/1cd106da592604cedae90f3f3a1aa0c8b15165dc

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
